### ISSUE TITLE
ISSUES WITH ALIGMENT IN AUTORNC

### ISSUE THREAD

**Issue by amuguruza009** [Elcock-Lab/AutoRNC#1]
Dear authors,
We are having some issues trying to run our own example. Apparently, it is not able to align our sequence but we are not able to understand what is going wrong in the alignment process. We believe the program is using the wrong UniProt code for the alignment (P0A6P9), but we are not sure how we can change it.
The output we are getting in the nohup.out file is this one:

 CHECK setting            1          60          60 A           0
 Now examining alignment: test.f_TEMPLATE_ahemodel.001.out                                           
 AHE HERE 001
 AHE HERE 002########################################                                                  
 AHE HERE 002# Program: needle                                                                         
 AHE HERE 002# Rundate: Wed  4 Sep 2019 13:54:09                                                       
 AHE HERE 002# Commandline: needle                                                                     
 AHE HERE 002#    [-asequence] P0A6P9.fasta                                                            
 AHE HERE 002#    [-bsequence] TEMPLATE_ahemodel.001.fasta                                             
 AHE HERE 002#    -gapopen 10.0                                                                        
 AHE HERE 002#    -gapextend 0.5                                                                       
 AHE HERE 002#    [-outfile] P0A6P9_TEMPLATE_ahemodel.001.out                                          
 AHE HERE 002# Align_format: srspair                                                                   
 AHE HERE 002# Report_file: P0A6P9_TEMPLATE_ahemodel.001.out                                           
 AHE HERE 002########################################                                                  
 AHE HERE 002                                                                                          
 AHE HERE 002#=======================================                                                  
 AHE HERE 002#                                                                                         
 AHE HERE 002# Aligned_sequences: 2                                                                    
 AHE HERE 002# 1: ENO_ECOLI                                                                            
 AHE HERE 002# 2: protein.fasta                                                                        
 AHE HERE 002# Matrix: EBLOSUM62                                                                       
 AHE HERE 002# Gap_penalty: 10.0                                                                       
 AHE HERE 002# Extend_penalty: 0.5                                                                     
 AHE HERE 002#                                                                                         
 AHE HERE 002# Length: 432                                                                             
 AHE HERE 002# Identity:     431/432 (99.8%)                                                           
 AHE HERE 002# Similarity:   431/432 (99.8%)                                                           
 AHE HERE 002# Gaps:           1/432 ( 0.2%)                                                           
 AHE HERE 002# Score: 2162.0                                                                           
 AHE HERE 002#                                                                                         
 AHE HERE 002#                                                                                         
 AHE HERE 002#=======================================                                                  
 AHE HERE 002                                                                                          
 ENO_ECOLI          1 GILGSGFALKVQEQHRQKHFEKRRNPAAGLIQSAWRFYATNLSRTDLHST     50            
                      ||||||||||||||||||||||||||||||||||||||||||||||||||                   
 protein.fasta      1 GILGSGFALKVQEQHRQKHFEKRRNPAAGLIQSAWRFYATNLSRTDLHST     50            
 ALIGN G           1             1
 ALIGN I           2             2
 ALIGN L           3             3
 ALIGN G           4             4
 ALIGN S           5             5
 ALIGN G           6             6
 ALIGN F           7             7
 ALIGN A           8             8
 ALIGN L           9             9
 ALIGN K          10            10
 ALIGN V          11            11
 ALIGN Q          12            12
 ALIGN E          13            13
 ALIGN Q          14            14
 ALIGN H          15            15
 ALIGN R          16            16
 ALIGN Q          17            17
 ALIGN K          18            18
 ALIGN H          19            19
 ALIGN F          20            20
 ALIGN E          21            21
 ALIGN K          22            22
 ALIGN R          23            23
 ALIGN R          24            24
 ALIGN N          25            25
 ALIGN P          26            26
 ALIGN A          27            27
 ALIGN A          28            28
 ALIGN G          29            29
 ALIGN L          30            30
 ALIGN I          31            31
 ALIGN Q          32            32
 ALIGN S          33            33
 ALIGN A          34            34
 ALIGN W          35            35
 ALIGN R          36            36
 ALIGN F          37            37
 ALIGN Y          38            38
 ALIGN A          39            39
 ALIGN T          40            40
 ALIGN N          41            41
 ALIGN L          42            42
 ALIGN S          43            43
 ALIGN R          44            44
 ALIGN T          45            45
 ALIGN D          46            46
 ALIGN L          47            47
 ALIGN H          48            48
 ALIGN S          49            49
 ALIGN T          50            50
 AHE HERE 002                                                                                          
 ENO_ECOLI         51 WQYYERTVTVPMYRE                                       100            
                      |||||||||||||||                                                      
 protein.fasta     51 WQYYERTVTVPMYRE                                       100            
 ALIGN W          51            51
 ALIGN Q          52            52
 ALIGN Y          53            53
 ALIGN Y          54            54
 ALIGN E          55            55
 ALIGN R          56            56
 ALIGN T          57            57
 ALIGN V          58            58
 ALIGN T          59            59
 ALIGN V          60            60
 ALIGN P          61            61
 ALIGN M          62            62
 ALIGN Y          63            63
 ALIGN R          64            64
 ALIGN E          65 E          65
 HELP ME            1          65          65           1           1
 HANG ON           65          60 test.f_TEMPLATE_ahemodel.001.out                                           
 first number should match second number above

**Comment by Elcock-Lab** [comment]
Sorry that you're having trouble - it's tough to diagnose this without seeing the input - how about sending me an email and we'll see if we can "zoom" to get this sorted out - best - Adrian
 
send email to: adrian-elcock@uiowa.edu

**Comment by amuguruza009** [comment]
Dear Adrian,

Thank you so much for your kind answer.
I am sending you the fasta file and the PDB. Let me know if you need
anything else.

Best wishes,

Arantza

**Comment by amuguruza009** [comment]
Hello,

In case it's necessary, I'll also add the command we have been trying to
run with these input files:

/home/markelgi/AutoRNC-main/SOURCE/make_comfile_AHEMODEL_nascent_chains_for_release_final_2023.exe
test 65 64 list_of_blocks list_of_ss_elems
\'/home/markelgi/AutoRNC-main/5UYM_L24/\'
\'/home/markelgi/AutoRNC-main/My_Example/\'
\'/home/markelgi/AutoRNC-main/SOURCE/\'
\'/home/markelgi/AutoRNC-main/DIPEPTIDES/\' 0 1 yes 2.00 3.00 5 1

The input files attached above were renamed to test.fasta and test.pdb to
run this.

Thanks in advance and best wishes,

Markel

**Comment by Elcock-Lab** [comment]
Arantza and Markel - thanks for your messages - i ddin't get the .fasta and/or the .pdb file - can you please resend them directly to my email address (don't use GitHub) : adrian-elcock@uiowa.edu - I still think this would be easier to solve via zoom but if that doesn't work for you then I can probably figure things out from your input files - by the way, have you successfully run any of the examples that we provided? - best - Adrian

**Comment by Elcock-Lab** [comment]
Arantza and Markel - I just sent a message to you via email - I think the issue is that the code expects the input .fasta to have a maximum of 60 residues per line - if the sequence is longer then it must be broken up onto multiple lines - it's probably also safer to stick with the generic filenames P12345.fasta and P12345.pdb or any other names that have 6 characters - best - Adrian
